export const banks =  [
        {
            code: "120001",
            name: "9mobile 9Payment Service Bank",
            slug: "9mobile-9payment-service-bank-ng",
            longCode: "120001",
            logo: null,
        },
        {
            code: "801",
            name: "Abbey Mortgage Bank",
            slug: "abbey-mortgage-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "51204",
            name: "Above Only MFB",
            slug: "above-only-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "51312",
            name: "Abulesoro MFB",
            slug: "abulesoro-mfb-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "044",
            name: "Access Bank",
            slug: "access-bank",
            longCode: "044150149",
            logo: null,
        },
        {
            code: "063",
            name: "Access Bank (Diamond)",
            slug: "access-bank-diamond",
            longCode: "063150162",
            logo: null,
        },
        {
            code: "602",
            name: "Accion Microfinance Bank",
            slug: "accion-microfinance-bank-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "50036",
            name: "Ahmadu Bello University Microfinance Bank",
            slug: "ahmadu-bello-university-microfinance-bank-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "120004",
            name: "Airtel Smartcash PSB",
            slug: "airtel-smartcash-psb-ng",
            longCode: "120004",
            logo: null,
        },
        {
            code: "51336",
            name: "AKU Microfinance Bank",
            slug: "aku-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "035A",
            name: "ALAT by WEMA",
            slug: "alat-by-wema",
            longCode: "035150103",
            logo: null,
        },
        {
            code: "090629",
            name: "Amegy Microfinance Bank",
            slug: "amegy-microfinance-bank-ng",
            longCode: "090629",
            logo: null,
        },
        {
            code: "50926",
            name: "Amju Unique MFB",
            slug: "amju-unique-mfb",
            longCode: "511080896",
            logo: null,
        },
        {
            code: "51341",
            name: "AMPERSAND MICROFINANCE BANK",
            slug: "ampersand-microfinance-bank-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "50083",
            name: "Aramoko MFB",
            slug: "aramoko-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "401",
            name: "ASO Savings and Loans",
            slug: "asosavings",
            longCode: "",
            logo: null,
        },
        {
            code: "MFB50094",
            name: "Astrapolaris MFB LTD",
            slug: "astrapolaris-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "51229",
            name: "Bainescredit MFB",
            slug: "bainescredit-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "50117",
            name: "Banc Corp Microfinance Bank",
            slug: "banc-corp-microfinance-bank-ng",
            longCode: "50117",
            logo: null,
        },
        {
            code: "50931",
            name: "Bowen Microfinance Bank",
            slug: "bowen-microfinance-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "FC40163",
            name: "Branch International Financial Services Limited",
            slug: "branch",
            longCode: "",
            logo: null,
        },
        {
            code: "565",
            name: "Carbon",
            slug: "carbon",
            longCode: "",
            logo: null,
        },
        {
            code: "865",
            name: "CASHCONNECT MFB",
            slug: "cashconnect-mfb-ng",
            longCode: "865",
            logo: null,
        },
        {
            code: "50823",
            name: "CEMCS Microfinance Bank",
            slug: "cemcs-microfinance-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "50171",
            name: "Chanelle Microfinance Bank Limited",
            slug: "chanelle-microfinance-bank-limited-ng",
            longCode: "50171",
            logo: null,
        },
        {
            code: "312",
            name: "Chikum Microfinance bank",
            slug: "chikum-microfinance-bank-ng",
            longCode: "null",
            logo: null,
        },
        {
            code: "023",
            name: "Citibank Nigeria",
            slug: "citibank-nigeria",
            longCode: "023150005",
            logo: null,
        },
        {
            code: "50910",
            name: "Consumer Microfinance Bank",
            slug: "consumer-microfinance-bank-ng",
            longCode: "50910",
            logo: null,
        },
        {
            code: "50204",
            name: "Corestep MFB",
            slug: "corestep-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "559",
            name: "Coronation Merchant Bank",
            slug: "coronation-merchant-bank-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "FC40128",
            name: "County Finance Limited",
            slug: "county-finance-limited",
            longCode: "",
            logo: null,
        },
        {
            code: "51297",
            name: "Crescent MFB",
            slug: "crescent-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "50162",
            name: "Dot Microfinance Bank",
            slug: "dot-microfinance-bank-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "050",
            name: "Ecobank Nigeria",
            slug: "ecobank-nigeria",
            longCode: "050150010",
            logo: null,
        },
        {
            code: "50263",
            name: "Ekimogun MFB",
            slug: "ekimogun-mfb-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "098",
            name: "Ekondo Microfinance Bank",
            slug: "ekondo-microfinance-bank-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "50126",
            name: "Eyowo",
            slug: "eyowo",
            longCode: "",
            logo: null,
        },
        {
            code: "51318",
            name: "Fairmoney Microfinance Bank",
            slug: "fairmoney-microfinance-bank-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "070",
            name: "Fidelity Bank",
            slug: "fidelity-bank",
            longCode: "070150003",
            logo: null,
        },
        {
            code: "51314",
            name: "Firmus MFB",
            slug: "firmus-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "011",
            name: "First Bank of Nigeria",
            slug: "first-bank-of-nigeria",
            longCode: "011151003",
            logo: null,
        },
        {
            code: "214",
            name: "First City Monument Bank",
            slug: "first-city-monument-bank",
            longCode: "214150018",
            logo: null,
        },
        {
            code: "413",
            name: "FirstTrust Mortgage Bank Nigeria",
            slug: "firsttrust-mortgage-bank-nigeria-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "50315",
            name: "FLOURISH MFB",
            slug: "flourish-mfb-ng",
            longCode: "50315",
            logo: null,
        },
        {
            code: "501",
            name: "FSDH Merchant Bank Limited",
            slug: "fsdh-merchant-bank-limited",
            longCode: "",
            logo: null,
        },
        {
            code: "812",
            name: "Gateway Mortgage Bank LTD",
            slug: "gateway-mortgage-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "00103",
            name: "Globus Bank",
            slug: "globus-bank",
            longCode: "103015001",
            logo: null,
        },
        {
            code: "100022",
            name: "GoMoney",
            slug: "gomoney",
            longCode: "",
            logo: null,
        },
        {
            code: "50739",
            name: "Goodnews Microfinance Bank",
            slug: "goodnews-microfinance-bank-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "562",
            name: "Greenwich Merchant Bank",
            slug: "greenwich-merchant-bank-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "058",
            name: "Guaranty Trust Bank",
            slug: "guaranty-trust-bank",
            longCode: "058152036",
            logo: null,
        },
        {
            code: "51251",
            name: "Hackman Microfinance Bank",
            slug: "hackman-microfinance-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "50383",
            name: "Hasal Microfinance Bank",
            slug: "hasal-microfinance-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "030",
            name: "Heritage Bank",
            slug: "heritage-bank",
            longCode: "030159992",
            logo: null,
        },
        {
            code: "120002",
            name: "HopePSB",
            slug: "hopepsb-ng",
            longCode: "120002",
            logo: null,
        },
        {
            code: "51244",
            name: "Ibile Microfinance Bank",
            slug: "ibile-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "50439",
            name: "Ikoyi Osun MFB",
            slug: "ikoyi-osun-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "50442",
            name: "Ilaro Poly Microfinance Bank",
            slug: "ilaro-poly-microfinance-bank-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "50453",
            name: "Imowo MFB",
            slug: "imowo-mfb-ng",
            longCode: "50453",
            logo: null,
        },
        {
            code: "50457",
            name: "Infinity MFB",
            slug: "infinity-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "301",
            name: "Jaiz Bank",
            slug: "jaiz-bank",
            longCode: "301080020",
            logo: null,
        },
        {
            code: "50502",
            name: "Kadpoly MFB",
            slug: "kadpoly-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "082",
            name: "Keystone Bank",
            slug: "keystone-bank",
            longCode: "082150017",
            logo: null,
        },
        {
            code: "50200",
            name: "Kredi Money MFB LTD",
            slug: "kredi-money-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "50211",
            name: "Kuda Bank",
            slug: "kuda-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "90052",
            name: "Lagos Building Investment Company Plc.",
            slug: "lbic-plc",
            longCode: "",
            logo: null,
        },
        {
            code: "50549",
            name: "Links MFB",
            slug: "links-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "031",
            name: "Living Trust Mortgage Bank",
            slug: "living-trust-mortgage-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "303",
            name: "Lotus Bank",
            slug: "lotus-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "50563",
            name: "Mayfair MFB",
            slug: "mayfair-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "50304",
            name: "Mint MFB",
            slug: "mint-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "50515",
            name: "Moniepoint MFB",
            slug: "moniepoint-mfb-ng",
            longCode: "null",
            logo: null,
        },
        {
            code: "120003",
            name: "MTN Momo PSB",
            slug: "mtn-momo-psb-ng",
            longCode: "120003",
            logo: null,
        },
        {
            code: "999992",
            name: "OPay Digital Services Limited (OPay)",
            slug: "paycom",
            longCode: "",
            logo: null,
        },
        {
            code: "107",
            name: "Optimus Bank Limited",
            slug: "optimus-bank-ltd",
            longCode: "00107",
            logo: null,
        },
        {
            code: "100002",
            name: "Paga",
            slug: "paga",
            longCode: "",
            logo: null,
        },
        {
            code: "999991",
            name: "PalmPay",
            slug: "palmpay",
            longCode: "",
            logo: null,
        },
        {
            code: "104",
            name: "Parallex Bank",
            slug: "parallex-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "311",
            name: "Parkway - ReadyCash",
            slug: "parkway-ready-cash",
            longCode: "",
            logo: null,
        },
        {
            code: "50743",
            name: "Peace Microfinance Bank",
            slug: "peace-microfinance-bank-ng",
            longCode: "50743",
            logo: null,
        },
        {
            code: "51146",
            name: "Personal Trust MFB",
            slug: "personal-trust-mfb-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "50746",
            name: "Petra Mircofinance Bank Plc",
            slug: "petra-microfinance-bank-plc",
            longCode: "",
            logo: null,
        },
        {
            code: "268",
            name: "Platinum Mortgage Bank",
            slug: "platinum-mortgage-bank-ng",
            longCode: "null",
            logo: null,
        },
        {
            code: "076",
            name: "Polaris Bank",
            slug: "polaris-bank",
            longCode: "076151006",
            logo: null,
        },
        {
            code: "50864",
            name: "Polyunwana MFB",
            slug: "polyunwana-mfb-ng",
            longCode: "null",
            logo: null,
        },
        {
            code: "105",
            name: "PremiumTrust Bank",
            slug: "premiumtrust-bank-ng",
            longCode: "000031",
            logo: null,
        },
        {
            code: "101",
            name: "Providus Bank",
            slug: "providus-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "51293",
            name: "QuickFund MFB",
            slug: "quickfund-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "502",
            name: "Rand Merchant Bank",
            slug: "rand-merchant-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "90067",
            name: "Refuge Mortgage Bank",
            slug: "refuge-mortgage-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "50994",
            name: "Rephidim Microfinance Bank",
            slug: "rephidim",
            longCode: "221151615",
            logo: null,
        },
        {
            code: "51286",
            name: "Rigo Microfinance Bank Limited",
            slug: "rigo-microfinance-bank-limited-ng",
            longCode: "51286",
            logo: null,
        },
        {
            code: "50767",
            name: "ROCKSHIELD MICROFINANCE BANK",
            slug: "rockshield-microfinance-bank-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "125",
            name: "Rubies MFB",
            slug: "rubies-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "51113",
            name: "Safe Haven MFB",
            slug: "safe-haven-mfb-ng",
            longCode: "51113",
            logo: null,
        },
        {
            code: "951113",
            name: "Safe Haven Microfinance Bank Limited",
            slug: "safe-haven-microfinance-bank-limited-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "40165",
            name: "SAGE GREY FINANCE LIMITED",
            slug: "sage-grey-finance-limited-ng",
            longCode: "null",
            logo: null,
        },
        {
            code: "50582",
            name: "Shield MFB",
            slug: "shield-mfb-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "51062",
            name: "Solid Allianze MFB",
            slug: "solid-allianze-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "50800",
            name: "Solid Rock MFB",
            slug: "solid-rock-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "51310",
            name: "Sparkle Microfinance Bank",
            slug: "sparkle-microfinance-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "221",
            name: "Stanbic IBTC Bank",
            slug: "stanbic-ibtc-bank",
            longCode: "221159522",
            logo: null,
        },
        {
            code: "068",
            name: "Standard Chartered Bank",
            slug: "standard-chartered-bank",
            longCode: "068150015",
            logo: null,
        },
        {
            code: "51253",
            name: "Stellas MFB",
            slug: "stellas-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "232",
            name: "Sterling Bank",
            slug: "sterling-bank",
            longCode: "232150016",
            logo: null,
        },
        {
            code: "100",
            name: "Suntrust Bank",
            slug: "suntrust-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "50968",
            name: "Supreme MFB",
            slug: "supreme-mfb-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "302",
            name: "TAJ Bank",
            slug: "taj-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "090560",
            name: "Tanadi Microfinance Bank",
            slug: "tanadi-microfinance-bank-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "51269",
            name: "Tangerine Money",
            slug: "tangerine-money",
            longCode: "",
            logo: null,
        },
        {
            code: "51211",
            name: "TCF MFB",
            slug: "tcf-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "102",
            name: "Titan Bank",
            slug: "titan-bank",
            longCode: "",
            logo: null,
        },
        {
            code: "100039",
            name: "Titan Paystack",
            slug: "titan-paystack",
            longCode: "",
            logo: null,
        },
        {
            code: "50840",
            name: "U&C Microfinance Bank Ltd (U AND C MFB)",
            slug: "uc-microfinance-bank-ltd-u-and-c-mfb-ng",
            longCode: "50840",
            logo: null,
        },
        {
            code: "MFB51322",
            name: "Uhuru MFB",
            slug: "uhuru-mfb-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "50870",
            name: "Unaab Microfinance Bank Limited",
            slug: "unaab-microfinance-bank-limited-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "50871",
            name: "Unical MFB",
            slug: "unical-mfb",
            longCode: "",
            logo: null,
        },
        {
            code: "51316",
            name: "Unilag Microfinance Bank",
            slug: "unilag-microfinance-bank-ng",
            longCode: "",
            logo: null,
        },
        {
            code: "032",
            name: "Union Bank of Nigeria",
            slug: "union-bank-of-nigeria",
            longCode: "032080474",
            logo: null,
        },
        {
            code: "033",
            name: "United Bank For Africa",
            slug: "united-bank-for-africa",
            longCode: "033153513",
            logo: null,
        },
        {
            code: "215",
            name: "Unity Bank",
            slug: "unity-bank",
            longCode: "215154097",
            logo: null,
        },
        {
            code: "566",
            name: "VFD Microfinance Bank Limited",
            slug: "vfd",
            longCode: "",
            logo: null,
        },
        {
            code: "51355",
            name: "Waya Microfinance Bank",
            slug: "waya-microfinance-bank-ng",
            longCode: "51355",
            logo: null,
        },
        {
            code: "035",
            name: "Wema Bank",
            slug: "wema-bank",
            longCode: "035150103",
            logo: null,
        },
        {
            code: "057",
            name: "Zenith Bank",
            slug: "zenith-bank",
            longCode: "057150013",
            logo: null,
        },
        {
            code: "057",
            name: "Zenith Bank",
            slug: "zenith-bank-usd",
            longCode: "057150013",
            logo: null,
        },
    ]